2.Program for multiple catch with single try:
--------------------------------------------------------

public class Main {  
    public static void main(String[] args) {  
        //try block containing exception prone code
        try{    
            System.out.println("try Block:: Begin");  
            int myArray[]=new int[5];    
            System.out.println("Array element 10 : " + myArray[10]);
            myArray[5]=10/0;    
        } 
        //multiple catch blocks
        catch(ArithmeticException e)  
        {  
            System.out.println("Arithmetic Exception :: Divide by zero!!");  
        }
        catch(ArrayIndexOutOfBoundsException e)  
        {  
            System.out.println("ArrayIndexOutOfBounds :: Accessed index out of bounds");  
        } 
        catch(Exception e)  
        {  
            System.out.println("Exception :: " + e.getMessage ());  
        }       
        System.out.println("rest of the code");    
    }  
}  
-----------
output:

try Block::Begin
ArrayIndexOutOfBounds::Accesses index out of bounds
rest of the code