// Multiple TryCatch Example by Pavan Butke


package abCoreJava;

public class MultiTryCatch {

	public static void main(String args[]) {
		
		int A[] = {30, 20 , 10 , 40 , 0};
		
		try {
			int c=A[0]/A[2];
			System.out.println("Division is "+c);
			System.out.println(A[5]);
		}
		catch(ArithmeticException e) {
			
			System.out.println("Denominator should not be 0 ");
		}
		catch(ArrayIndexOutOfBoundsException e) {
			
			System.out.println("Index is Invalid ");
		}
		
		
		System.out.println("Bye");
	}
	
}


o/p -->

Division is 3
Index is Invalid 
Bye



class MultiCatch2{
	public static void main (String[] args) {
        try{
            System.out.println(4/0);
        }catch(ArithmeticException e)
        {
            System.out.println("ArithmeticException : divide by 0");
        }catch(Exception e)
        {
            System.out.println("Exception : divide by 0");
        }
   }
}

o/p==>

ArithmeticException: Divide by 0